// @routes-hash 8db0ec3da83333066a5655e8704c323a
import { Express, Request, Response, NextFunction, Router } from "express";

type RouteLoader = () => Promise<{ default: Router }>;

const route1: RouteLoader = () => import("./routes/agents/clearMemory");
const route2: RouteLoader = () => import("./routes/agents/getMemory");
const route3: RouteLoader = () => import("./routes/artStyle/addArtStyle");
const route4: RouteLoader = () => import("./routes/artStyle/editArtStyle");
const route5: RouteLoader = () => import("./routes/artStyle/extractStylePrompt");
const route6: RouteLoader = () => import("./routes/artStyle/getArtStyle");
const route7: RouteLoader = () => import("./routes/assets/addAssets");
const route8: RouteLoader = () => import("./routes/assets/addAudioAssets");
const route9: RouteLoader = () => import("./routes/assets/batchDelete");
const route10: RouteLoader = () => import("./routes/assets/batchGenerationData");
const route11: RouteLoader = () => import("./routes/assets/delAssets");
const route12: RouteLoader = () => import("./routes/assets/delImage");
const route13: RouteLoader = () => import("./routes/assets/getAssetsApi");
const route14: RouteLoader = () => import("./routes/assets/getImage");
const route15: RouteLoader = () => import("./routes/assets/getMaterialData");
const route16: RouteLoader = () => import("./routes/assets/pollingImageAssets");
const route17: RouteLoader = () => import("./routes/assets/pollingPromptAssets");
const route18: RouteLoader = () => import("./routes/assets/saveAssets");
const route19: RouteLoader = () => import("./routes/assets/updateAssets");
const route20: RouteLoader = () => import("./routes/assets/updateAudioAssets");
const route21: RouteLoader = () => import("./routes/assets/uploadClip");
const route22: RouteLoader = () => import("./routes/assetsGenerate/batchGenerateImageAssets");
const route23: RouteLoader = () => import("./routes/assetsGenerate/batchPolishAssetsPrompt");
const route24: RouteLoader = () => import("./routes/assetsGenerate/cancelGenerate");
const route25: RouteLoader = () => import("./routes/assetsGenerate/generateAssets");
const route26: RouteLoader = () => import("./routes/assetsGenerate/polishAssetsPrompt");
const route27: RouteLoader = () => import("./routes/common/getBigImage");
const route28: RouteLoader = () => import("./routes/cornerScape/batchBindAudio");
const route29: RouteLoader = () => import("./routes/cornerScape/getAllAssets");
const route30: RouteLoader = () => import("./routes/cornerScape/pollingAudio");
const route31: RouteLoader = () => import("./routes/cornerScape/updateAssetsAudio");
const route32: RouteLoader = () => import("./routes/general/generalStatistics");
const route33: RouteLoader = () => import("./routes/general/getSingleProject");
const route34: RouteLoader = () => import("./routes/general/updateProject");
const route35: RouteLoader = () => import("./routes/login/login");
const route36: RouteLoader = () => import("./routes/modelSelect/getModelDetail");
const route37: RouteLoader = () => import("./routes/modelSelect/getModelList");
const route38: RouteLoader = () => import("./routes/novel/addNovel");
const route39: RouteLoader = () => import("./routes/novel/batchDeleteNovel");
const route40: RouteLoader = () => import("./routes/novel/delNovel");
const route41: RouteLoader = () => import("./routes/novel/event/batchDeleteEvent");
const route42: RouteLoader = () => import("./routes/novel/event/deletEvent");
const route43: RouteLoader = () => import("./routes/novel/event/generateEvents");
const route44: RouteLoader = () => import("./routes/novel/event/getEvent");
const route45: RouteLoader = () => import("./routes/novel/getNovel");
const route46: RouteLoader = () => import("./routes/novel/getNovelData");
const route47: RouteLoader = () => import("./routes/novel/getNovelEventState");
const route48: RouteLoader = () => import("./routes/novel/getNovelIndex");
const route49: RouteLoader = () => import("./routes/novel/updateNovel");
const route50: RouteLoader = () => import("./routes/other/deleteAllData");
const route51: RouteLoader = () => import("./routes/other/getVersion");
const route52: RouteLoader = () => import("./routes/production/assets/batchGenerateAssetsImage");
const route53: RouteLoader = () => import("./routes/production/assets/deleteAssetsDireve");
const route54: RouteLoader = () => import("./routes/production/assets/pollingImage");
const route55: RouteLoader = () => import("./routes/production/assets/updateAssetsUrl");
const route56: RouteLoader = () => import("./routes/production/editImage/generateFlowImage");
const route57: RouteLoader = () => import("./routes/production/editImage/getImageDefaultModle");
const route58: RouteLoader = () => import("./routes/production/editImage/getImageFlow");
const route59: RouteLoader = () => import("./routes/production/editImage/saveImageFlow");
const route60: RouteLoader = () => import("./routes/production/editImage/updateImageFlow");
const route61: RouteLoader = () => import("./routes/production/editImage/uploadImage");
const route62: RouteLoader = () => import("./routes/production/getFlowData");
const route63: RouteLoader = () => import("./routes/production/getStoryboardData");
const route64: RouteLoader = () => import("./routes/production/saveFlowData");
const route65: RouteLoader = () => import("./routes/production/storyboard/addStoryboard");
const route66: RouteLoader = () => import("./routes/production/storyboard/batchAddStoryboardInfo");
const route67: RouteLoader = () => import("./routes/production/storyboard/batchDelete");
const route68: RouteLoader = () => import("./routes/production/storyboard/batchGenerateImage");
const route69: RouteLoader = () => import("./routes/production/storyboard/downPreviewImage");
const route70: RouteLoader = () => import("./routes/production/storyboard/editStoryboardInfo");
const route71: RouteLoader = () => import("./routes/production/storyboard/getStoryboardData");
const route72: RouteLoader = () => import("./routes/production/storyboard/pollingImage");
const route73: RouteLoader = () => import("./routes/production/storyboard/previewImage");
const route74: RouteLoader = () => import("./routes/production/storyboard/removeFrame");
const route75: RouteLoader = () => import("./routes/production/storyboard/updateStoryboardUrl");
const route76: RouteLoader = () => import("./routes/production/workbench/addTrack");
const route77: RouteLoader = () => import("./routes/production/workbench/batchGeneratePrompt");
const route78: RouteLoader = () => import("./routes/production/workbench/batchGenerateVideo");
const route79: RouteLoader = () => import("./routes/production/workbench/checkVideoPrompt");
const route80: RouteLoader = () => import("./routes/production/workbench/checkVideoStateList");
const route81: RouteLoader = () => import("./routes/production/workbench/deleteTrack");
const route82: RouteLoader = () => import("./routes/production/workbench/delVideo");
const route83: RouteLoader = () => import("./routes/production/workbench/generateVideo");
const route84: RouteLoader = () => import("./routes/production/workbench/generateVideoPrompt");
const route85: RouteLoader = () => import("./routes/production/workbench/getAudioBindAssetsList");
const route86: RouteLoader = () => import("./routes/production/workbench/getFileUrl");
const route87: RouteLoader = () => import("./routes/production/workbench/getGenerateData");
const route88: RouteLoader = () => import("./routes/production/workbench/getVideoList");
const route89: RouteLoader = () => import("./routes/production/workbench/selectVideo");
const route90: RouteLoader = () => import("./routes/production/workbench/updateVideoDuration");
const route91: RouteLoader = () => import("./routes/production/workbench/updateVideoPrompt");
const route92: RouteLoader = () => import("./routes/project/addDirectorManual");
const route93: RouteLoader = () => import("./routes/project/addProject");
const route94: RouteLoader = () => import("./routes/project/addVisualManual");
const route95: RouteLoader = () => import("./routes/project/deleteDirectorManual");
const route96: RouteLoader = () => import("./routes/project/deleteVisualManual");
const route97: RouteLoader = () => import("./routes/project/delProject");
const route98: RouteLoader = () => import("./routes/project/editDirectorlManual");
const route99: RouteLoader = () => import("./routes/project/editProject");
const route100: RouteLoader = () => import("./routes/project/editVisualManual");
const route101: RouteLoader = () => import("./routes/project/getModelDetails");
const route102: RouteLoader = () => import("./routes/project/getProject");
const route103: RouteLoader = () => import("./routes/project/getVisualManual");
const route104: RouteLoader = () => import("./routes/project/queryDirectorManual");
const route105: RouteLoader = () => import("./routes/project/visualManual");
const route106: RouteLoader = () => import("./routes/script/addScript");
const route107: RouteLoader = () => import("./routes/script/batchAddScript");
const route108: RouteLoader = () => import("./routes/script/delScript");
const route109: RouteLoader = () => import("./routes/script/exportScript");
const route110: RouteLoader = () => import("./routes/script/extractAssets");
const route111: RouteLoader = () => import("./routes/script/getAiRegex");
const route112: RouteLoader = () => import("./routes/script/getScrptApi");
const route113: RouteLoader = () => import("./routes/script/pollScriptAssets");
const route114: RouteLoader = () => import("./routes/script/updateScript");
const route115: RouteLoader = () => import("./routes/scriptAgent/getPlanData");
const route116: RouteLoader = () => import("./routes/scriptAgent/setPlanData");
const route117: RouteLoader = () => import("./routes/scriptAgent/updateData");
const route118: RouteLoader = () => import("./routes/setting/about/checkUpdate");
const route119: RouteLoader = () => import("./routes/setting/about/downloadApp");
const route120: RouteLoader = () => import("./routes/setting/agentDeploy/agentSetKey");
const route121: RouteLoader = () => import("./routes/setting/agentDeploy/deployAgentModel");
const route122: RouteLoader = () => import("./routes/setting/agentDeploy/getAgentDeploy");
const route123: RouteLoader = () => import("./routes/setting/agentDeploy/getAgentUseMode");
const route124: RouteLoader = () => import("./routes/setting/agentDeploy/updateAgentModel");
const route125: RouteLoader = () => import("./routes/setting/agentDeploy/updateUseMode");
const route126: RouteLoader = () => import("./routes/setting/dbConfig/clearData");
const route127: RouteLoader = () => import("./routes/setting/dbConfig/clearTable");
const route128: RouteLoader = () => import("./routes/setting/dbConfig/dbInfo");
const route129: RouteLoader = () => import("./routes/setting/dbConfig/exportData");
const route130: RouteLoader = () => import("./routes/setting/dbConfig/importData");
const route131: RouteLoader = () => import("./routes/setting/dev/getSwitchAiDevTool");
const route132: RouteLoader = () => import("./routes/setting/dev/updateSwitchAiDevTool");
const route133: RouteLoader = () => import("./routes/setting/fileManagement/openFolder");
const route134: RouteLoader = () => import("./routes/setting/getTextModel");
const route135: RouteLoader = () => import("./routes/setting/loginConfig/getUser");
const route136: RouteLoader = () => import("./routes/setting/loginConfig/updateUserPwd");
const route137: RouteLoader = () => import("./routes/setting/memoryConfig/delAllMemory");
const route138: RouteLoader = () => import("./routes/setting/memoryConfig/getMemory");
const route139: RouteLoader = () => import("./routes/setting/memoryConfig/sureMemory");
const route140: RouteLoader = () => import("./routes/setting/modelMap/bindingPrompt");
const route141: RouteLoader = () => import("./routes/setting/modelMap/deletePrompt");
const route142: RouteLoader = () => import("./routes/setting/modelMap/getImageAndVideoModel");
const route143: RouteLoader = () => import("./routes/setting/modelMap/getPromptList");
const route144: RouteLoader = () => import("./routes/setting/modelMap/savePrompt");
const route145: RouteLoader = () => import("./routes/setting/modelMap/updatePrompt");
const route146: RouteLoader = () => import("./routes/setting/ossConfig/getOssConfig");
const route147: RouteLoader = () => import("./routes/setting/ossConfig/saveOssConfig");
const route148: RouteLoader = () => import("./routes/setting/promptManage/getPrompt");
const route149: RouteLoader = () => import("./routes/setting/promptManage/updatePrompt");
const route150: RouteLoader = () => import("./routes/setting/skillManagement/getSkillContent");
const route151: RouteLoader = () => import("./routes/setting/skillManagement/getSkillList");
const route152: RouteLoader = () => import("./routes/setting/skillManagement/saveSkillContent");
const route153: RouteLoader = () => import("./routes/setting/vendorConfig/addVendor");
const route154: RouteLoader = () => import("./routes/setting/vendorConfig/addVendorModel");
const route155: RouteLoader = () => import("./routes/setting/vendorConfig/deleteVendor");
const route156: RouteLoader = () => import("./routes/setting/vendorConfig/delVendorModel");
const route157: RouteLoader = () => import("./routes/setting/vendorConfig/enableVendor");
const route158: RouteLoader = () => import("./routes/setting/vendorConfig/getCodeByLink");
const route159: RouteLoader = () => import("./routes/setting/vendorConfig/getVendorList");
const route160: RouteLoader = () => import("./routes/setting/vendorConfig/modelTest");
const route161: RouteLoader = () => import("./routes/setting/vendorConfig/modelTest/imageTest");
const route162: RouteLoader = () => import("./routes/setting/vendorConfig/modelTest/textTest");
const route163: RouteLoader = () => import("./routes/setting/vendorConfig/modelTest/videoTest");
const route164: RouteLoader = () => import("./routes/setting/vendorConfig/updateCode");
const route165: RouteLoader = () => import("./routes/setting/vendorConfig/updateVendorInputs");
const route166: RouteLoader = () => import("./routes/setting/vendorConfig/upVendorModel");
const route167: RouteLoader = () => import("./routes/task/getProject");
const route168: RouteLoader = () => import("./routes/task/getTaskApi");
const route169: RouteLoader = () => import("./routes/task/getTaskCategories");
const route170: RouteLoader = () => import("./routes/task/taskDetails");
const route171: RouteLoader = () => import("./routes/test/test");

const lazyRoute = (loader: RouteLoader) => {
  let router: Router | null = null;
  return async (req: Request, res: Response, next: NextFunction) => {
    try {
      if (!router) router = (await loader()).default;
      return router(req, res, next);
    } catch (e) {
      next(e);
    }
  };
};

export default async (app: Express) => {
  app.use("/api/agents/clearMemory", lazyRoute(route1));
  app.use("/api/agents/getMemory", lazyRoute(route2));
  app.use("/api/artStyle/addArtStyle", lazyRoute(route3));
  app.use("/api/artStyle/editArtStyle", lazyRoute(route4));
  app.use("/api/artStyle/extractStylePrompt", lazyRoute(route5));
  app.use("/api/artStyle/getArtStyle", lazyRoute(route6));
  app.use("/api/assets/addAssets", lazyRoute(route7));
  app.use("/api/assets/addAudioAssets", lazyRoute(route8));
  app.use("/api/assets/batchDelete", lazyRoute(route9));
  app.use("/api/assets/batchGenerationData", lazyRoute(route10));
  app.use("/api/assets/delAssets", lazyRoute(route11));
  app.use("/api/assets/delImage", lazyRoute(route12));
  app.use("/api/assets/getAssetsApi", lazyRoute(route13));
  app.use("/api/assets/getImage", lazyRoute(route14));
  app.use("/api/assets/getMaterialData", lazyRoute(route15));
  app.use("/api/assets/pollingImageAssets", lazyRoute(route16));
  app.use("/api/assets/pollingPromptAssets", lazyRoute(route17));
  app.use("/api/assets/saveAssets", lazyRoute(route18));
  app.use("/api/assets/updateAssets", lazyRoute(route19));
  app.use("/api/assets/updateAudioAssets", lazyRoute(route20));
  app.use("/api/assets/uploadClip", lazyRoute(route21));
  app.use("/api/assetsGenerate/batchGenerateImageAssets", lazyRoute(route22));
  app.use("/api/assetsGenerate/batchPolishAssetsPrompt", lazyRoute(route23));
  app.use("/api/assetsGenerate/cancelGenerate", lazyRoute(route24));
  app.use("/api/assetsGenerate/generateAssets", lazyRoute(route25));
  app.use("/api/assetsGenerate/polishAssetsPrompt", lazyRoute(route26));
  app.use("/api/common/getBigImage", lazyRoute(route27));
  app.use("/api/cornerScape/batchBindAudio", lazyRoute(route28));
  app.use("/api/cornerScape/getAllAssets", lazyRoute(route29));
  app.use("/api/cornerScape/pollingAudio", lazyRoute(route30));
  app.use("/api/cornerScape/updateAssetsAudio", lazyRoute(route31));
  app.use("/api/general/generalStatistics", lazyRoute(route32));
  app.use("/api/general/getSingleProject", lazyRoute(route33));
  app.use("/api/general/updateProject", lazyRoute(route34));
  app.use("/api/login/login", lazyRoute(route35));
  app.use("/api/modelSelect/getModelDetail", lazyRoute(route36));
  app.use("/api/modelSelect/getModelList", lazyRoute(route37));
  app.use("/api/novel/addNovel", lazyRoute(route38));
  app.use("/api/novel/batchDeleteNovel", lazyRoute(route39));
  app.use("/api/novel/delNovel", lazyRoute(route40));
  app.use("/api/novel/event/batchDeleteEvent", lazyRoute(route41));
  app.use("/api/novel/event/deletEvent", lazyRoute(route42));
  app.use("/api/novel/event/generateEvents", lazyRoute(route43));
  app.use("/api/novel/event/getEvent", lazyRoute(route44));
  app.use("/api/novel/getNovel", lazyRoute(route45));
  app.use("/api/novel/getNovelData", lazyRoute(route46));
  app.use("/api/novel/getNovelEventState", lazyRoute(route47));
  app.use("/api/novel/getNovelIndex", lazyRoute(route48));
  app.use("/api/novel/updateNovel", lazyRoute(route49));
  app.use("/api/other/deleteAllData", lazyRoute(route50));
  app.use("/api/other/getVersion", lazyRoute(route51));
  app.use("/api/production/assets/batchGenerateAssetsImage", lazyRoute(route52));
  app.use("/api/production/assets/deleteAssetsDireve", lazyRoute(route53));
  app.use("/api/production/assets/pollingImage", lazyRoute(route54));
  app.use("/api/production/assets/updateAssetsUrl", lazyRoute(route55));
  app.use("/api/production/editImage/generateFlowImage", lazyRoute(route56));
  app.use("/api/production/editImage/getImageDefaultModle", lazyRoute(route57));
  app.use("/api/production/editImage/getImageFlow", lazyRoute(route58));
  app.use("/api/production/editImage/saveImageFlow", lazyRoute(route59));
  app.use("/api/production/editImage/updateImageFlow", lazyRoute(route60));
  app.use("/api/production/editImage/uploadImage", lazyRoute(route61));
  app.use("/api/production/getFlowData", lazyRoute(route62));
  app.use("/api/production/getStoryboardData", lazyRoute(route63));
  app.use("/api/production/saveFlowData", lazyRoute(route64));
  app.use("/api/production/storyboard/addStoryboard", lazyRoute(route65));
  app.use("/api/production/storyboard/batchAddStoryboardInfo", lazyRoute(route66));
  app.use("/api/production/storyboard/batchDelete", lazyRoute(route67));
  app.use("/api/production/storyboard/batchGenerateImage", lazyRoute(route68));
  app.use("/api/production/storyboard/downPreviewImage", lazyRoute(route69));
  app.use("/api/production/storyboard/editStoryboardInfo", lazyRoute(route70));
  app.use("/api/production/storyboard/getStoryboardData", lazyRoute(route71));
  app.use("/api/production/storyboard/pollingImage", lazyRoute(route72));
  app.use("/api/production/storyboard/previewImage", lazyRoute(route73));
  app.use("/api/production/storyboard/removeFrame", lazyRoute(route74));
  app.use("/api/production/storyboard/updateStoryboardUrl", lazyRoute(route75));
  app.use("/api/production/workbench/addTrack", lazyRoute(route76));
  app.use("/api/production/workbench/batchGeneratePrompt", lazyRoute(route77));
  app.use("/api/production/workbench/batchGenerateVideo", lazyRoute(route78));
  app.use("/api/production/workbench/checkVideoPrompt", lazyRoute(route79));
  app.use("/api/production/workbench/checkVideoStateList", lazyRoute(route80));
  app.use("/api/production/workbench/deleteTrack", lazyRoute(route81));
  app.use("/api/production/workbench/delVideo", lazyRoute(route82));
  app.use("/api/production/workbench/generateVideo", lazyRoute(route83));
  app.use("/api/production/workbench/generateVideoPrompt", lazyRoute(route84));
  app.use("/api/production/workbench/getAudioBindAssetsList", lazyRoute(route85));
  app.use("/api/production/workbench/getFileUrl", lazyRoute(route86));
  app.use("/api/production/workbench/getGenerateData", lazyRoute(route87));
  app.use("/api/production/workbench/getVideoList", lazyRoute(route88));
  app.use("/api/production/workbench/selectVideo", lazyRoute(route89));
  app.use("/api/production/workbench/updateVideoDuration", lazyRoute(route90));
  app.use("/api/production/workbench/updateVideoPrompt", lazyRoute(route91));
  app.use("/api/project/addDirectorManual", lazyRoute(route92));
  app.use("/api/project/addProject", lazyRoute(route93));
  app.use("/api/project/addVisualManual", lazyRoute(route94));
  app.use("/api/project/deleteDirectorManual", lazyRoute(route95));
  app.use("/api/project/deleteVisualManual", lazyRoute(route96));
  app.use("/api/project/delProject", lazyRoute(route97));
  app.use("/api/project/editDirectorlManual", lazyRoute(route98));
  app.use("/api/project/editProject", lazyRoute(route99));
  app.use("/api/project/editVisualManual", lazyRoute(route100));
  app.use("/api/project/getModelDetails", lazyRoute(route101));
  app.use("/api/project/getProject", lazyRoute(route102));
  app.use("/api/project/getVisualManual", lazyRoute(route103));
  app.use("/api/project/queryDirectorManual", lazyRoute(route104));
  app.use("/api/project/visualManual", lazyRoute(route105));
  app.use("/api/script/addScript", lazyRoute(route106));
  app.use("/api/script/batchAddScript", lazyRoute(route107));
  app.use("/api/script/delScript", lazyRoute(route108));
  app.use("/api/script/exportScript", lazyRoute(route109));
  app.use("/api/script/extractAssets", lazyRoute(route110));
  app.use("/api/script/getAiRegex", lazyRoute(route111));
  app.use("/api/script/getScrptApi", lazyRoute(route112));
  app.use("/api/script/pollScriptAssets", lazyRoute(route113));
  app.use("/api/script/updateScript", lazyRoute(route114));
  app.use("/api/scriptAgent/getPlanData", lazyRoute(route115));
  app.use("/api/scriptAgent/setPlanData", lazyRoute(route116));
  app.use("/api/scriptAgent/updateData", lazyRoute(route117));
  app.use("/api/setting/about/checkUpdate", lazyRoute(route118));
  app.use("/api/setting/about/downloadApp", lazyRoute(route119));
  app.use("/api/setting/agentDeploy/agentSetKey", lazyRoute(route120));
  app.use("/api/setting/agentDeploy/deployAgentModel", lazyRoute(route121));
  app.use("/api/setting/agentDeploy/getAgentDeploy", lazyRoute(route122));
  app.use("/api/setting/agentDeploy/getAgentUseMode", lazyRoute(route123));
  app.use("/api/setting/agentDeploy/updateAgentModel", lazyRoute(route124));
  app.use("/api/setting/agentDeploy/updateUseMode", lazyRoute(route125));
  app.use("/api/setting/dbConfig/clearData", lazyRoute(route126));
  app.use("/api/setting/dbConfig/clearTable", lazyRoute(route127));
  app.use("/api/setting/dbConfig/dbInfo", lazyRoute(route128));
  app.use("/api/setting/dbConfig/exportData", lazyRoute(route129));
  app.use("/api/setting/dbConfig/importData", lazyRoute(route130));
  app.use("/api/setting/dev/getSwitchAiDevTool", lazyRoute(route131));
  app.use("/api/setting/dev/updateSwitchAiDevTool", lazyRoute(route132));
  app.use("/api/setting/fileManagement/openFolder", lazyRoute(route133));
  app.use("/api/setting/getTextModel", lazyRoute(route134));
  app.use("/api/setting/loginConfig/getUser", lazyRoute(route135));
  app.use("/api/setting/loginConfig/updateUserPwd", lazyRoute(route136));
  app.use("/api/setting/memoryConfig/delAllMemory", lazyRoute(route137));
  app.use("/api/setting/memoryConfig/getMemory", lazyRoute(route138));
  app.use("/api/setting/memoryConfig/sureMemory", lazyRoute(route139));
  app.use("/api/setting/modelMap/bindingPrompt", lazyRoute(route140));
  app.use("/api/setting/modelMap/deletePrompt", lazyRoute(route141));
  app.use("/api/setting/modelMap/getImageAndVideoModel", lazyRoute(route142));
  app.use("/api/setting/modelMap/getPromptList", lazyRoute(route143));
  app.use("/api/setting/modelMap/savePrompt", lazyRoute(route144));
  app.use("/api/setting/modelMap/updatePrompt", lazyRoute(route145));
  app.use("/api/setting/ossConfig/getOssConfig", lazyRoute(route146));
  app.use("/api/setting/ossConfig/saveOssConfig", lazyRoute(route147));
  app.use("/api/setting/promptManage/getPrompt", lazyRoute(route148));
  app.use("/api/setting/promptManage/updatePrompt", lazyRoute(route149));
  app.use("/api/setting/skillManagement/getSkillContent", lazyRoute(route150));
  app.use("/api/setting/skillManagement/getSkillList", lazyRoute(route151));
  app.use("/api/setting/skillManagement/saveSkillContent", lazyRoute(route152));
  app.use("/api/setting/vendorConfig/addVendor", lazyRoute(route153));
  app.use("/api/setting/vendorConfig/addVendorModel", lazyRoute(route154));
  app.use("/api/setting/vendorConfig/deleteVendor", lazyRoute(route155));
  app.use("/api/setting/vendorConfig/delVendorModel", lazyRoute(route156));
  app.use("/api/setting/vendorConfig/enableVendor", lazyRoute(route157));
  app.use("/api/setting/vendorConfig/getCodeByLink", lazyRoute(route158));
  app.use("/api/setting/vendorConfig/getVendorList", lazyRoute(route159));
  app.use("/api/setting/vendorConfig/modelTest", lazyRoute(route160));
  app.use("/api/setting/vendorConfig/modelTest/imageTest", lazyRoute(route161));
  app.use("/api/setting/vendorConfig/modelTest/textTest", lazyRoute(route162));
  app.use("/api/setting/vendorConfig/modelTest/videoTest", lazyRoute(route163));
  app.use("/api/setting/vendorConfig/updateCode", lazyRoute(route164));
  app.use("/api/setting/vendorConfig/updateVendorInputs", lazyRoute(route165));
  app.use("/api/setting/vendorConfig/upVendorModel", lazyRoute(route166));
  app.use("/api/task/getProject", lazyRoute(route167));
  app.use("/api/task/getTaskApi", lazyRoute(route168));
  app.use("/api/task/getTaskCategories", lazyRoute(route169));
  app.use("/api/task/taskDetails", lazyRoute(route170));
  app.use("/api/test/test", lazyRoute(route171));
}
